/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActiveRouteImport } from './routes/active'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as DocumentationRouteImport } from './routes/documentation'
import { Route as FocusRouteImport } from './routes/focus'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as InstallRouteImport } from './routes/install'
import { Route as OptimizerRouteImport } from './routes/optimizer'
import { Route as ReportRouteImport } from './routes/report'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TablesRouteImport } from './routes/tables'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as TodayRouteImport } from './routes/today'
import { Route as TopicsRouteImport } from './routes/topics'
import { Route as ItemItemIdRouteImport } from './routes/item.$itemId'
import { Route as ApiPublicPushCronRouteImport } from './routes/api/public/push-cron'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActiveRoute = ActiveRouteImport.update({
  id: '/active',
  path: '/active',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationRoute = DocumentationRouteImport.update({
  id: '/documentation',
  path: '/documentation',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusRoute = FocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const OptimizerRoute = OptimizerRouteImport.update({
  id: '/optimizer',
  path: '/optimizer',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TablesRoute = TablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsRoute = TopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemItemIdRoute = ItemItemIdRouteImport.update({
  id: '/item/$itemId',
  path: '/item/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushCronRoute = ApiPublicPushCronRouteImport.update({
  id: '/api/public/push-cron',
  path: '/api/public/push-cron',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/active': typeof ActiveRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/daily': typeof DailyRoute
  '/documentation': typeof DocumentationRoute
  '/focus': typeof FocusRoute
  '/goals': typeof GoalsRoute
  '/install': typeof InstallRoute
  '/optimizer': typeof OptimizerRoute
  '/report': typeof ReportRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/tables': typeof TablesRoute
  '/tasks': typeof TasksRoute
  '/today': typeof TodayRoute
  '/topics': typeof TopicsRoute
  '/item/$itemId': typeof ItemItemIdRoute
  '/api/public/push-cron': typeof ApiPublicPushCronRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/active': typeof ActiveRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/daily': typeof DailyRoute
  '/documentation': typeof DocumentationRoute
  '/focus': typeof FocusRoute
  '/goals': typeof GoalsRoute
  '/install': typeof InstallRoute
  '/optimizer': typeof OptimizerRoute
  '/report': typeof ReportRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/tables': typeof TablesRoute
  '/tasks': typeof TasksRoute
  '/today': typeof TodayRoute
  '/topics': typeof TopicsRoute
  '/item/$itemId': typeof ItemItemIdRoute
  '/api/public/push-cron': typeof ApiPublicPushCronRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/active': typeof ActiveRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/daily': typeof DailyRoute
  '/documentation': typeof DocumentationRoute
  '/focus': typeof FocusRoute
  '/goals': typeof GoalsRoute
  '/install': typeof InstallRoute
  '/optimizer': typeof OptimizerRoute
  '/report': typeof ReportRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/tables': typeof TablesRoute
  '/tasks': typeof TasksRoute
  '/today': typeof TodayRoute
  '/topics': typeof TopicsRoute
  '/item/$itemId': typeof ItemItemIdRoute
  '/api/public/push-cron': typeof ApiPublicPushCronRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/active'
    | '/assistant'
    | '/auth'
    | '/calendar'
    | '/daily'
    | '/documentation'
    | '/focus'
    | '/goals'
    | '/install'
    | '/optimizer'
    | '/report'
    | '/search'
    | '/settings'
    | '/tables'
    | '/tasks'
    | '/today'
    | '/topics'
    | '/item/$itemId'
    | '/api/public/push-cron'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/active'
    | '/assistant'
    | '/auth'
    | '/calendar'
    | '/daily'
    | '/documentation'
    | '/focus'
    | '/goals'
    | '/install'
    | '/optimizer'
    | '/report'
    | '/search'
    | '/settings'
    | '/tables'
    | '/tasks'
    | '/today'
    | '/topics'
    | '/item/$itemId'
    | '/api/public/push-cron'
  id:
    | '__root__'
    | '/'
    | '/active'
    | '/assistant'
    | '/auth'
    | '/calendar'
    | '/daily'
    | '/documentation'
    | '/focus'
    | '/goals'
    | '/install'
    | '/optimizer'
    | '/report'
    | '/search'
    | '/settings'
    | '/tables'
    | '/tasks'
    | '/today'
    | '/topics'
    | '/item/$itemId'
    | '/api/public/push-cron'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActiveRoute: typeof ActiveRoute
  AssistantRoute: typeof AssistantRoute
  AuthRoute: typeof AuthRoute
  CalendarRoute: typeof CalendarRoute
  DailyRoute: typeof DailyRoute
  DocumentationRoute: typeof DocumentationRoute
  FocusRoute: typeof FocusRoute
  GoalsRoute: typeof GoalsRoute
  InstallRoute: typeof InstallRoute
  OptimizerRoute: typeof OptimizerRoute
  ReportRoute: typeof ReportRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  TablesRoute: typeof TablesRoute
  TasksRoute: typeof TasksRoute
  TodayRoute: typeof TodayRoute
  TopicsRoute: typeof TopicsRoute
  ItemItemIdRoute: typeof ItemItemIdRoute
  ApiPublicPushCronRoute: typeof ApiPublicPushCronRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/active': {
      id: '/active'
      path: '/active'
      fullPath: '/active'
      preLoaderRoute: typeof ActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation': {
      id: '/documentation'
      path: '/documentation'
      fullPath: '/documentation'
      preLoaderRoute: typeof DocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus': {
      id: '/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof FocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/optimizer': {
      id: '/optimizer'
      path: '/optimizer'
      fullPath: '/optimizer'
      preLoaderRoute: typeof OptimizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tables': {
      id: '/tables'
      path: '/tables'
      fullPath: '/tables'
      preLoaderRoute: typeof TablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics': {
      id: '/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof TopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/item/$itemId': {
      id: '/item/$itemId'
      path: '/item/$itemId'
      fullPath: '/item/$itemId'
      preLoaderRoute: typeof ItemItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push-cron': {
      id: '/api/public/push-cron'
      path: '/api/public/push-cron'
      fullPath: '/api/public/push-cron'
      preLoaderRoute: typeof ApiPublicPushCronRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActiveRoute: ActiveRoute,
  AssistantRoute: AssistantRoute,
  AuthRoute: AuthRoute,
  CalendarRoute: CalendarRoute,
  DailyRoute: DailyRoute,
  DocumentationRoute: DocumentationRoute,
  FocusRoute: FocusRoute,
  GoalsRoute: GoalsRoute,
  InstallRoute: InstallRoute,
  OptimizerRoute: OptimizerRoute,
  ReportRoute: ReportRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  TablesRoute: TablesRoute,
  TasksRoute: TasksRoute,
  TodayRoute: TodayRoute,
  TopicsRoute: TopicsRoute,
  ItemItemIdRoute: ItemItemIdRoute,
  ApiPublicPushCronRoute: ApiPublicPushCronRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
