/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActiveRouteImport } from './routes/active'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DocumentationRouteImport } from './routes/documentation'
import { Route as FocusRouteImport } from './routes/focus'
import { Route as OptimizerRouteImport } from './routes/optimizer'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TablesRouteImport } from './routes/tables'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as TopicsRouteImport } from './routes/topics'
import { Route as ItemItemIdRouteImport } from './routes/item.$itemId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActiveRoute = ActiveRouteImport.update({
  id: '/active',
  path: '/active',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationRoute = DocumentationRouteImport.update({
  id: '/documentation',
  path: '/documentation',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusRoute = FocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const OptimizerRoute = OptimizerRouteImport.update({
  id: '/optimizer',
  path: '/optimizer',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TablesRoute = TablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsRoute = TopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemItemIdRoute = ItemItemIdRouteImport.update({
  id: '/item/$itemId',
  path: '/item/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/active': typeof ActiveRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/documentation': typeof DocumentationRoute
  '/focus': typeof FocusRoute
  '/optimizer': typeof OptimizerRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/tables': typeof TablesRoute
  '/tasks': typeof TasksRoute
  '/topics': typeof TopicsRoute
  '/item/$itemId': typeof ItemItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/active': typeof ActiveRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/documentation': typeof DocumentationRoute
  '/focus': typeof FocusRoute
  '/optimizer': typeof OptimizerRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/tables': typeof TablesRoute
  '/tasks': typeof TasksRoute
  '/topics': typeof TopicsRoute
  '/item/$itemId': typeof ItemItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/active': typeof ActiveRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/documentation': typeof DocumentationRoute
  '/focus': typeof FocusRoute
  '/optimizer': typeof OptimizerRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/tables': typeof TablesRoute
  '/tasks': typeof TasksRoute
  '/topics': typeof TopicsRoute
  '/item/$itemId': typeof ItemItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/active'
    | '/assistant'
    | '/auth'
    | '/documentation'
    | '/focus'
    | '/optimizer'
    | '/search'
    | '/settings'
    | '/tables'
    | '/tasks'
    | '/topics'
    | '/item/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/active'
    | '/assistant'
    | '/auth'
    | '/documentation'
    | '/focus'
    | '/optimizer'
    | '/search'
    | '/settings'
    | '/tables'
    | '/tasks'
    | '/topics'
    | '/item/$itemId'
  id:
    | '__root__'
    | '/'
    | '/active'
    | '/assistant'
    | '/auth'
    | '/documentation'
    | '/focus'
    | '/optimizer'
    | '/search'
    | '/settings'
    | '/tables'
    | '/tasks'
    | '/topics'
    | '/item/$itemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActiveRoute: typeof ActiveRoute
  AssistantRoute: typeof AssistantRoute
  AuthRoute: typeof AuthRoute
  DocumentationRoute: typeof DocumentationRoute
  FocusRoute: typeof FocusRoute
  OptimizerRoute: typeof OptimizerRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  TablesRoute: typeof TablesRoute
  TasksRoute: typeof TasksRoute
  TopicsRoute: typeof TopicsRoute
  ItemItemIdRoute: typeof ItemItemIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/active': {
      id: '/active'
      path: '/active'
      fullPath: '/active'
      preLoaderRoute: typeof ActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation': {
      id: '/documentation'
      path: '/documentation'
      fullPath: '/documentation'
      preLoaderRoute: typeof DocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus': {
      id: '/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof FocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/optimizer': {
      id: '/optimizer'
      path: '/optimizer'
      fullPath: '/optimizer'
      preLoaderRoute: typeof OptimizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tables': {
      id: '/tables'
      path: '/tables'
      fullPath: '/tables'
      preLoaderRoute: typeof TablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics': {
      id: '/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof TopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/item/$itemId': {
      id: '/item/$itemId'
      path: '/item/$itemId'
      fullPath: '/item/$itemId'
      preLoaderRoute: typeof ItemItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActiveRoute: ActiveRoute,
  AssistantRoute: AssistantRoute,
  AuthRoute: AuthRoute,
  DocumentationRoute: DocumentationRoute,
  FocusRoute: FocusRoute,
  OptimizerRoute: OptimizerRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  TablesRoute: TablesRoute,
  TasksRoute: TasksRoute,
  TopicsRoute: TopicsRoute,
  ItemItemIdRoute: ItemItemIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
